import { PRODUCTS_URL } from "../constants";
import { apiSlice } from "./apiSlice";

export const productsApiSlice = apiSlice.injectEndpoints({
    endpoints: (builder)=>({
        getProducts: builder.query({
            query: ()=>({
                url: PRODUCTS_URL,
            }),
            keepUnusedDataFor: 5  //it will keep the data in cache for 5s if user need again in mentioned time range, data will be retrieved from cache
        }),
        getProductDetails: builder.query({
            query: (id)=>({
                url: `${PRODUCTS_URL}/${id}`,
            }),
            keepUnusedDataFor: 5
        })
    })
});

export const { useGetProductsQuery, useGetProductDetailsQuery } = productsApiSlice;//it is convention to name like this : use<name-of-endpoint>Query here endpoint is getProducts 
//useGetProductsQuery is a React hook generated by the getProducts endpoint defined in the productsApiSlice
