
import { PRODUCTS_URL, UPLOAD_URL } from "../constants";
import { apiSlice } from "./apiSlice";

export const productsApiSlice = apiSlice.injectEndpoints({
    endpoints: (builder)=>({
        getProducts: builder.query({
            query: ()=>({
                url: PRODUCTS_URL,
            }),
            providesTags: ['Products'], //it will invalidate the cache when we create or update a product
            keepUnusedDataFor: 5  //it will keep the data in cache for 5s if user need again in mentioned time range, data will be retrieved from cache
        }),
        getProductDetails: builder.query({
            query: (id)=>({
                url: `${PRODUCTS_URL}/${id}`,
            }),
            keepUnusedDataFor: 5
        }),
        createProduct: builder.mutation({
            query:()=>({
                url:PRODUCTS_URL,
                method:'POST',
            }),
            invalidatesTags: ['Product']
        }),
        updateProduct: builder.mutation({
            query: (data)=>({
                url: `${PRODUCTS_URL}/${data.productId}`,
                method:'PUT',
                body: data,
            }),
            invalidatesTags: ['Products' ]

        }),

        uploadProductImage: builder.mutation({
            query: (data)=>({
                url: `${UPLOAD_URL}`,
                method:'POST',
                body: data,
            }),
            
        }),
        deleteProduct: builder.mutation({
            query: (id)=>({
                url: `${PRODUCTS_URL}/${id}`,
                method:'DELETE',
            }),
        }),
    }),
});

export const { useGetProductsQuery, 
    useGetProductDetailsQuery, 
    useCreateProductMutation, 
    useUpdateProductMutation, 
    useUploadProductImageMutation,
    useDeleteProductMutation
} = productsApiSlice;//it is convention to name like this : use<name-of-endpoint>Query here endpoint is getProducts 
//useGetProductsQuery is a React hook generated by the getProducts endpoint defined in the productsApiSlice
